on: [push]
jobs:
  build_and_release_esqshell:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest
    name: "Build and Release esqshell on ${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: 0.8.156
      - name: Build
        run: ./esqshell/script/build.sh ${{ matrix.os }}
      - name: Release
        uses: tzafrirben/babashka-docker-action@v1.1
        id: release
        with:
          bb_src: "esqshell/script/babashka/release_artifact.clj"
      - name: Release output
        run: echo "${{ steps.release.outputs.bb_out }}"
