on: [push]
jobs:
  build_and_release_esqshell:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest
    name: "Build and Release esqshell on ${{ matrix.os }}"
    defaults:
        run:
          working-directory: ./esqshell
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: 0.8.156
      - name: Build
        run: ./script/build.sh ${{ matrix.os }}
      - name: Release
        run: bb ./script/babashka/release_artifact.clj
